services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb

    ports:
      - "27007:27017"

    volumes:
      - mongodb:/data/db

    networks:
      - backend

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    restart: always

networks:
  backend:

volumes:
  mongodb: